language: bash
before_script:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
- sudo pip install awscli
- mkdir output
- ln -s resume.tex index.tex
- ln -s resume.tex guyhf.tex
script:
- perl ltoh.pl index.tex
- pdflatex --output-directory=output guyhf.tex
deploy:
  on:
    branch: master
  provider: s3
  region: us-west-2
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: resume.guyhf.com
  acl: public_read
  skip_cleanup: true
  local_dir: output
  cache_control: max-age=21600
env:
  global:
  - secure: U1D4B7yWxW6E/FaSX7OScZPN1YP2FRXGSpizG2Ftt5nEFLX0gxccqQvAu04HatTc3miQJDtEnB6xJXcwzBMby5JyWXGHgr7kVPZC88ANC6ZxGwYFfCOhhq9KFkn4UI0ppWpzGkGydeJaItTou5asIqOMuxIm/kaHr63iQDAJ4wQ4trnRhQIb6VhqclYlBJsDnlYxlJyem8EjwsmzDeOideICWnmYg9Irlbu+oX/SNe58EVY86SPZHiVtxzAPWxddqbhOZgPFnhGRU4XFYzZN5d0XGuj8FFwbGINJDtYcUIil539wzcWFjoQi+B0N1jveI2bSj+K9z+6s0oNPiz0Kq4/x7pI6cpRDJNqGUmic8E+bB3RBNIpHKY7jXL8CZi0kxhoBmc0IPzH4V7eP7M3ZenqUcXikuF4kyYJOYFUntxMFyBRGRLjLoXtGcN45hvD05oyJ3X8i1c7ekhxQRjSYIE6MRQftbnIrFzK3NL0UgOPjUwme0ysH7KvhljOy6KFTA37+ys5ybMzAeQzFAD3FQPlJ0fn0kROtfKfM9B6DW4PgjlkGMlBP5Dmm5ol1ZrZXcyez1Kg48wKdrcxsz4cMyOsDJbNfzyuFbV4CZIJvpjZwJIvFmLP67ots9ElCmR+l20OQsIoJ5gKHPY4GBnXxdkHHoSXEzBFuKGH+4a9IANw=
  - secure: Q2X/ApIfdcBLKGlam1SacdxqlNDpzersiwM6nBfJw61mlIe39ZyezFmgcQFkDPaaKVrpjAus3lNPeWY+QwfNSyoLWkLMJJ/5VP0N8sn3+jCRcQhxB8T2VMLkw7IApHwXL2E3B5g7YKmlwr50BvDG1reQG0SHjrYg6zqKxhPUlWqGkfFb78sGVxTdM0bR3lLogQR8pP0fSy2Jci4Aiq/hWDBOLpvJuBPfSUexxRmLr8m5RIGArssSTQFE/NbaF5Tkt4dR84h8u2vvzG4QcjlLjUD0z0rggCEX47SbDzKYYXTYSwp3XwOWLTwlGASs6mCJAbnNFb36caZ6/qJi5X2r6ccfgLVGcOl4VL9ECXsDbLPb7n1v4/QEgrdQmCoTbU1J8rcSb2x89PQLLtw9UZ6Jsx0w9Trr815KN4Gst5sbMHMMYzZr2iCYnQf0y3xgkWhQsWKAu0YNmNO5j6mgFLzs+AFaUzr4kLpmQViRKkIMwfidZRasEnocb8edKx+zkOeUlPirnkVuQrWo8TnDkvz7FpDsQKCQHQQZT2/Ooz0f4MOufcKnu+/nvD2F90t6ywcCm0knZ7a2p7C3fE7BqoMMPTEEzvI71QUQi3aKWbNb1XiY/jWiTSV05KcNbDmK5Ot4Tooq4q/MEA8NnF2zN0Rc16ipBdrjAKUcEMxnLiiIIZg=
